### ISSUE TITLE
function for autocomplete missing

### ISSUE THREAD

**Issue by hvbe** [AddSearch/js-client-library#1]
Hi there

Will the API eventually get a function for the autocomplete (https://www.addsearch.com/support/api-reference/#autocomplete) endpoint as well?

Best regards

**Comment by anttiai** [comment]
Hey,

Yes. The plan is to add the autocomplete function as soon as possible. We're adding a "size" parameter to the API endpoint to control the number of autocomplete results returned. We want to get that change live first and change the API client right after that. I'll keep you updated.

**Comment by anttiai** [comment]
Autocomplete functions added in the release 0.2.4
- https://github.com/AddSearch/js-client-library/releases/tag/v0.2.4
- https://github.com/AddSearch/js-client-library#fetch-custom-field-autocompletion
