### ISSUE TITLE
[Feature]Insert, Update, Delete

### ISSUE THREAD

**Issue by shinriyo** [AddSearch/js-client-library#13]
Does it Insert, Update, Delete?
I can't find the source code and the document.

**Comment by anttiai** [comment]
The current version (0.4.x) is only for search. We're planning to add Insert, Update, and Delete capabilities in the following months. 

In the meanwhile, you can manage documents by posting manually to appropriate API endpoints, e.g. https://www.addsearch.com/docs/api/indexing-create/ to index a new document.

**Comment by shinriyo** [comment]
@anttiai 
Thank you for replying.
I see. I must pure TypeScript code.

**Comment by anttiai** [comment]
Indexing API functions (insert, update, delete, fetch) were added in the [release v0.5.0](https://github.com/AddSearch/js-client-library/releases/tag/v0.5.0)
