### ISSUE TITLE
Fix dependabot issue: node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor

### ISSUE THREAD

**Issue by gergokee** [AddSearch/js-client-library#30]
Hi,
Can you replace isomorphic-fetch so that we don't use deprecated node-fetch which exposes our app to vulnerabilities?
Thank you!

**Comment by haoAddsearch** [comment]
Thank you @gergokee!
The issue has been fixed in version 0.7.0, I'm closing the issue now.
